repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      args: [--line-length=79]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      exclude: ^(alembic/|tests/|fastapi_cache/)

# -   repo: https://github.com/pycqa/isort
#     rev: 5.12.0
#     hooks:
#     - id: isort
#       name: isort (python)
#       entry: isort --fgw 3 --multi-line 3
